apiVersion: batch.example.com/v1
kind: ReplicaManager
metadata:
  name: replicamanager-sample
spec:
  containerName: test
  count: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure