# permissions for end users to edit replicamanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: replicamanager-editor-role
rules:
- apiGroups:
  - batch.example.com
  resources:
  - replicamanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.example.com
  resources:
  - replicamanagers/status
  verbs:
  - get
