
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch.example.com
  resources:
  - replicamanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.example.com
  resources:
  - replicamanagers/finalizers
  verbs:
  - update
- apiGroups:
  - batch.example.com
  resources:
  - replicamanagers/status
  verbs:
  - get
  - patch
  - update
